version: "3.8"

services:   
  sherlock:
    build: .
    volumes:
      - ${HOST_PROJECT_PATH:-.}:/app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db: 
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "host=db user=postgres password=password dbname=crm port=5432 sslmode=disable TimeZone=America/Sao_Paulo"
      JWT_SECRET: "my_dev_super_secret"
      REDIS_ADDR: "redis:6379"
      COMPOSE_FILE: "/workspace/docker-compose.yml"
      HOST_PROJECT_PATH: "${PWD:-.}"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000/api/v1"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - api

volumes:
  pgdata: